from tkinter import *
app = Tk()
app.geometry("500x300")
app.title("Menu Python")
menu_bar = Menu(app)
menu_fichier = Menu(menu_bar, tearoff=0)
menu_fichier.add_command(label="Nouveau")
menu_fichier.add_command(label="Ouvrir")
menu_fichier.add_separator()
menu_fichier.add_command(label="Quitter", command=app.quit)
menu_bar.add_cascade(label="Fichier", menu=menu_fichier)
menu_aide = Menu(menu_bar, tearoff=0)
menu_aide.add_command(label="À propos")
menu_bar.add_cascade(label="Aide", menu=menu_aide)
app.config(menu=menu_bar)
app.mainloop()